version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - echo Build started...
      - mvn clean package -DskipTests

  post_build:
    - echo Build completed

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**